name: dryice
version: 1.8.0
author: Mike Mitterer <office@mikemitterer.at>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/MikeMitterer/dryice

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  logging: ^0.11.0

dev_dependencies:
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0

  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
