name: dryice
version: 2.0.17
author: Mike Mitterer <office@mikemitterer.at>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/MikeMitterer/dryice

environment:
  sdk: ">=2.0.0 <3.0.0"
  
dependencies:
  logging: '>=0.11.3 <1.0.0'

  reflectable: '>=2.0.4 <3.0.0'
    # git: git@github.com:dart-lang/reflectable.git
    # path: /Volumes/Daten/DevLocal/DevDart/reflectable

dev_dependencies:
  test: any

  console_log_handler: ^1.0.0

  build_runner: any
  build_test: any
  build_web_compilers: any

