name: dryice_sample_cmdline
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
description: Dice-Test on the cmdline
homepage: https://github.com/ltackmann/dice

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  dryice:
    path: ../..
    
dev_dependencies:

  logging_handlers: ^0.8.0
  console_log_handler: ^1.0.0

  build_runner: any
  build_test: any
  build_web_compilers: any

